DROP DATABASE IF EXISTS pho_db;

CREATE DATABASE pho_db;

USE pho_db;

CREATE TABLE pho(
    id INT NOT NULL AUTO_INCREMENT,
    pho_name VARCHAR(35) NOT NULL,
    slurped BOOLEAN DEFAULT false,
    PRIMARY KEY (id)
);